services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3333:80/tcp"
    environment:
      TZ: 'Europe/Ljubljana'
      WEBPASSWORD: ''
      QUERY_LOGGING: 'false'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped